### ISSUE TITLE
CMake does not find the blaze headers to compile the test case

### ISSUE THREAD

**Issue by diehlpk** [tjolsen/BlazeIterative#2]
[ 50%] Building CXX object tests/CMakeFiles/blz_iter_test.dir/main.cpp.o
cd /home/Patrick/git/BlazeIterative/tests && /usr/bin/c++   -I/home/Patrick/git/BlazeIterative/blaze_iterative  -std=gnu++14 -o CMakeFiles/blz_iter_test.dir/main.cpp.o -c /home/Patrick/git/BlazeIterative/tests/main.cpp
In file included from /home/Patrick/git/BlazeIterative/blaze_iterative/BlazeIterative.hpp:8:0,
                 from /home/Patrick/git/BlazeIterative/tests/main.cpp:5:
/home/Patrick/git/BlazeIterative/blaze_iterative/IterativeCommon.hpp:8:10: fatal error: blaze/Blaze.h: No such file or directory
 #include "blaze/Blaze.h"
          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by diehlpk** [comment]
With this pull request, the test compiles again

```
Scanning dependencies of target blz_iter_test
[ 50%] Building CXX object tests/CMakeFiles/blz_iter_test.dir/main.cpp.o
[100%] Linking CXX executable blz_iter_test
[100%] Built target blz_iter_test
```

**Comment by tjolsen** [comment]
This should be resolved now.
