### ISSUE TITLE
Installation target is missing 

### ISSUE THREAD

**Issue by diehlpk** [tjolsen/BlazeIterative#4]
One should specify a install dir in cmake and make install will copy all headers to the specified install directory like in blaze.

**Comment by tjolsen** [comment]
Hi diehlpk, sorry for the late response. This project doesn't get a lot of my time, unfortunately. I've learned how modern cmake works over the past few weeks and have updated the build system for this project. Let me know if it works for you now. The readme has instructions for build/installation and using the library from another cmake project.
